stages:
  - build

# test frontend:
#   stage: test
#   image: node:20
#   script:
#     - cd Frontend
#     - yarn install
#     - yarn test
    
build frontend:
  stage: build
  image: node:20
  script:
    - cd Frontend
    - yarn install
    - yarn build
  artifacts:
    paths: 
      - build/ # before you through away the docker container, make sure you save this `build` folder somewhere

# deploy frontend to netlify:
#   stage: deploy
#   image: node:20
#   script:
#     - cd Frontend
#     - yarn install
#     - yarn global add netlify-cli
#     - netlify deploy --dir=build --prod



