stages:
  - test
  - build
  - deploy

test_frontend:
  stage: test
  image: node:20
  script:
    - cd Frontend
    - yarn install
    - yarn test
    
build_frontend:
  stage: build
  image: node:20
  script:
    - cd Frontend
    - yarn install
    - yarn build

deploy_frontend_to_netlify:
  stage: deploy
  image: node:20
  script:
    - cd Frontend
    - yarn add -g netlify-cli
    - netlify deploy --dir=build --prod



