stages:
  - check_variables
  - install_az_cli
  - deploy

variables:
  AZURE_WEBAPP_NAME: "maqasid"
  RESOURCE_GROUP: "makassed-resource-group"
  AZURE_CLIENT_ID: "7ae3fbcc-53dd-42c3-bb11-3064a7858156"
  AZURE_TENANT_ID: "076a96db-b735-4cdb-a841-a2a80ee5eafe"
  AZURE_CLIENT_SECRET: "3La8Q~6tLmoD-ZNUkhPFK9PalNQSKX8qTo3WvcwZ"
  AZURE_SUBSCRIPTION_ID: "d0dd10d9-ebc7-4a41-be64-ecd2cbdb5df8"
  CONNECTION_STRING: "Data Source=sqlserver-maqasid.database.windows.net,1433;Initial Catalog=sqldb-maqasid;User ID=admin.maqasid;Password=Krankenhaus@123"
  CI_REPOSITORY_URL: "https://gitlab.com/makassed/makassed.git"
  CI_COMMIT_REF_NAME: "main"

check_variables:
  stage: check_variables
  script:
    - echo "AZURE_CLIENT_ID:" + $AZURE_CLIENT_ID
    - echo "AZURE_CLIENT_SECRET:" + $AZURE_CLIENT_SECRET"
    - echo "AZURE_TENANT_ID:" + $AZURE_TENANT_ID"
    - echo "AZURE_SUBSCRIPTION_ID:" + $AZURE_SUBSCRIPTION_ID"
    - echo "CI_REPOSITORY_URL:" + $CI_REPOSITORY_URL"
  only:
    - main

install_az_cli:
  stage: install_az_cli
  image: mcr.microsoft.com/azure-cli:latest
  script:
    - az --version  # Display Azure CLI version for verification
  only:
    - main

deploy:
  stage: deploy
  only:
    - main
  script:
    - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - az webapp config appsettings set --name $AZURE_WEBAPP_NAME --resource-group $RESOURCE_GROUP --settings ASPNETCORE_ENVIRONMENT=Production
    - az webapp config appsettings set --name $AZURE_WEBAPP_NAME --resource-group $RESOURCE_GROUP --settings ConnectionStrings.MakassedConnectionString=$CONNECTION_STRING
    - az webapp deployment source config --name $AZURE_WEBAPP_NAME --resource-group $RESOURCE_GROUP --repo-url $CI_REPOSITORY_URL --branch $CI_COMMIT_REF_NAME --manual-integration
    - az webapp deployment source sync --name $AZURE_WEBAPP_NAME --resource-group $RESOURCE_GROUP
    - az webapp restart --name $AZURE_WEBAPP_NAME --resource-group $RESOURCE_GROUP
