stages:
  - build

variables:
  # Define any environment variables needed for your build
  REACT_APP_API_URL: "https://example.com/api"

before_script:
  # Install dependencies
  - cd Frontend/
  - yarn install

build:
  stage: build
  script:
    # Build the React project
    - yarn build

# Add additional stages or jobs as needed
# ...
