stages:
  - build

variables:
  REACT_APP_API_URL: "https://example.com/api"

before_script:
  - apt-get update -qy
  - apt-get install -y curl
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - nvm install v20.7.0
  - npm install -g yarn@3.0.1 typescript@^4.3.4

build:
  stage: build
  script:
    - cd Frontend/
    - yarn install
    - yarn build
