deploy-job:
  image: mcr.microsoft.com/azure-cli
  variables:
    AZURE_CLIENT_ID: $AZURE_CLIENT_ID
    AZURE_CLIENT_SECRET : $AZURE_CLIENT_SECRET 
    AZURE_TENANT_ID: $AZURE_TENANT_ID
    AZURE_SUBSCRIPTION_ID: $AZURE_SUBSCRIPTION_ID
  stage: deploy
  script:
    - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET  --tenant $AZURE_TENANT_ID
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - az group list