stages:
  - setup
  - build

variables:
  # Define any environment variables needed for your build
  REACT_APP_API_URL: "https://example.com/api"

before_script:
  # Setup job installs Yarn and Node.js
  - apt-get update -qy
  - apt-get install -y nodejs
  - apt-get install -y npm
  - npm install -g yarn

setup:
  stage: setup
  script:
    - cd Frontend/
    - yarn install

build:
  stage: build
  script:
    # Build the React project
    - cd Frontend/
    - yarn build
