name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
 AZURE_WEBAPP_NAME: almakassed
 AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/checkout@v3
        with:
          dotnet-version: '7.x'

      - name: Restore
        run: dotnet restore ./Backend/MakassedBackend.sln

      - name: Build
        run: dotnet build ./Backend/MakassedBackend.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Backend/MakassedBackend.sln --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Login using Managed Identity
        uses: azure/login@v1
    
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_ALMAKASSED }}
         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
       
